// Offline component walkthrough: no authentication, backend, analytics, or model calls.
import assert from "node:assert/strict";
import { createRequire } from "node:module";
const { chromium } = createRequire(import.meta.url)(process.argv[2] || "playwright");
const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
try {
  const page = await browser.newPage({ viewport: { width: 393, height: 852 } });
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  const button = name => page.getByRole("button", { name, exact: true });
  const click = async name => button(name).click();
  const shot = async name => { await page.evaluate(() => document.fonts.ready); await page.screenshot({ path: `docs/growth-guidance-ux/${name}.png` }); };
  const home = async (query = "") => { await page.goto(`http://127.0.0.1:4173${query}`); await button("Check in").waitFor(); };
  const menu = async name => { await click("More"); await click(name); };
  await home();
  assert.equal(await page.getByRole("tab").count(), 0);
  assert.equal(await page.getByRole("button").count(), 3); // Close, More, one forward action.
  await shot("today");
  await click("Check in"); await page.getByRole("textbox").fill("A draft I want to keep.");
  await click("Back"); await click("Keep writing");
  assert.equal(await page.getByRole("textbox").inputValue(), "A draft I want to keep.");
  await shot("write"); await click("Back"); await click("Discard draft");
  await click("Check in"); assert.equal(await page.getByRole("textbox").inputValue(), "");
  await page.getByRole("textbox").fill("I said hello today."); await click("Send");
  await button("Done").waitFor(); await shot("response"); await click("Done");
  await click("Check in"); await page.getByRole("textbox").fill("A note about my attempt.");
  await click("Tried your step? Log an attempt"); await click("Partly"); await shot("check-in");
  assert.equal(await button("Continue").count(), 0);
  await click("Harder than expected");
  assert.equal(await page.getByRole("textbox").inputValue(), "A note about my attempt.");
  await click("Back"); await click("Back"); await click("Back");
  assert.equal(await page.getByRole("textbox").inputValue(), "A note about my attempt.");
  await click("Tried your step? Log an attempt"); await click("Did it"); await click("Easier than expected");
  await click("Submit report"); await click("Done");
  await menu("Ask for a different step"); await page.getByRole("textbox").fill("Make it easier. I only have a minute.");
  await click("Send"); await button("Confirm change").waitFor(); await shot("review-change");
  await click("Back"); assert.equal(await button("Check in").count(), 0);
  await click("Review suggestion"); await click("Keep my plan as it is"); await click("Done");
  await menu("About this step"); await click("I'll try this"); await button("Check in").waitFor();
  await menu("My direction"); await shot("direction"); await click("Back");
  await menu("Past check-ins"); await shot("journal"); await click("Back");
  await menu("Nearby opportunities"); await shot("events"); await click("Set up nearby opportunities");
  const availability = page.getByRole("textbox", { name: "Available days and times", exact: true });
  await availability.fill("Weekends only"); await click("Back"); await click("Keep editing");
  assert.equal(await availability.inputValue(), "Weekends only");
  await click("Back"); await click("Discard changes"); await click("Back");
  await home("?voice"); await click("Check in"); await shot("journal-mobile");
  await page.getByRole("textbox").fill("Keep this while I record."); await click("Use voice");
  await click("Keep writing");
  assert.equal(await page.getByRole("textbox").inputValue(), "Keep this while I record.");
  await click("Use voice");
  await page.getByRole("dialog").getByRole("button", { name: "Use voice", exact: true }).click();
  await button("Start recording").waitFor(); await shot("voice-intro");
  await click("Back"); await click("Stay here"); await click("Back"); await click("Leave");
  assert.equal(await page.getByRole("textbox").inputValue(), "");
  await home("?voice&transcript"); await click("Check in");
  await page.getByRole("textbox").fill("Replace this with voice."); await click("Use voice");
  await page.getByRole("dialog").getByRole("button", { name: "Use voice", exact: true }).click();
  await button("Send").waitFor(); await click("Send"); await click("Done");
  await click("Check in"); assert.equal(await page.getByRole("textbox").inputValue(), "");
  await home("?event"); await menu("Nearby opportunities"); await button("Use this as my next step").waitFor(); await shot("event-match");
  for (const reason of ["Too much right now", "Not relevant", "Too far", "Bad timing", "Wrong type of event", "This event is stale or incorrect"]) {
    await click("Not for me"); await click(reason); assert.equal(await button("Use this as my next step").count(), 0);
    await click("Find a suitable opportunity"); await button("Use this as my next step").waitFor();
  }
  await click("Use this as my next step"); await click("Cancel"); await click("Use this as my next step"); await click("Confirm change");
  assert.equal(await button("Use this as my next step").count(), 0);
  await home("?empty&voice"); await shot("empty"); await click("Check in"); await button("Use voice").waitFor();
  await page.getByRole("textbox").fill("A reflection without a step."); await click("Send"); await click("Done");
  await home("?voice"); await menu("About this step"); await click("Set this step aside"); await click("Set aside");
  await click("Check in"); await click("Use voice"); await button("Start recording").waitFor();
  await page.goto("http://127.0.0.1:4173?lang=it"); await button("Racconta come va").waitFor(); await shot("italian");
  await page.setViewportSize({ width: 320, height: 640 }); await shot("small-phone");
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.goto("http://127.0.0.1:4173?failure"); await button("Close").scrollIntoViewIfNeeded(); await shot("load-error");
  await click("Retry loading activity"); await button("Check in").waitFor();
  assert.deepEqual(errors, []);
  console.log("PASS: one primary home action/no tabs, writing/voice draft continuity, reports, pending review, menu destinations, events, empty/error recovery, Italian and narrow layout.");
} finally { await browser.close(); }
