// Uses the offline preview server; never authenticates or calls external services.
// node tests/growth-guidance-preview/check.mjs /path/to/playwright/index.js
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { mkdir } from "node:fs/promises";
const require = createRequire(import.meta.url);
const { chromium } = require(process.argv[2] || "playwright");
const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
const output = "docs/growth-guidance-ux";
await mkdir(output, { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const button = (name) => page.getByRole("button", { name, exact: true });
  const tab = (name) => page.getByRole("tab", { name, exact: true });
  const shot = async (name) => { await page.evaluate(() => document.fonts.ready); await page.screenshot({ path: `${output}/${name}.png` }); };
  await page.goto("http://127.0.0.1:4173");
  await button("I'll try this").waitFor();
  await shot("today");
  await button("I'll try this").click();
  await page.getByText("YOUR CHOSEN STEP", { exact: true }).waitFor();
  await tab("Journal").click();
  assert.equal(await page.getByText("ONE SMALL STEP", { exact: true }).count(), 0);
  await shot("journal");
  await button("Write an entry A thought, a small win, or something that felt hard.").click();
  await page.getByRole("textbox", { name: "Your journal entry" }).fill("A draft I want to keep.");
  await button("Back").click();
  await button("Keep writing").click();
  assert.equal(await page.getByRole("textbox").inputValue(), "A draft I want to keep.");
  await shot("write");
  await button("Back").click();
  await button("Discard draft").click();
  await page.getByText("Your journal", { exact: true }).waitFor();
  await button("Write an entry A thought, a small win, or something that felt hard.").click();
  assert.equal(await page.getByRole("textbox").inputValue(), "");
  await page.getByRole("textbox").fill("I said hello today and it felt good.");
  await button("Save & reflect").click();
  await page.getByText("A moment to reflect", { exact: true }).waitFor();
  await shot("response");
  await button("Back to today").click();
  await button("Check in on this step").click();
  await button("Partly").click();
  await button("Continue").click();
  await shot("check-in");
  await button("Harder than expected").click();
  await button("Continue").click();
  await page.getByRole("textbox").fill("I tried a short hello.");
  await button("Back").click();
  await button("Continue").click();
  assert.equal(await page.getByRole("textbox").inputValue(), "I tried a short hello.");
  await button("Submit report").click();
  await button("Back to today").click();
  await button("Adjust this step").click();
  await button("Make it easier").click();
  await page.getByRole("textbox").fill("I only have energy for a brief hello.");
  await button("Ask for guidance").click();
  await button("Confirm change").waitFor();
  await shot("review-change");
  await button("Keep my plan as it is").click();
  await button("Back to today").click();
  await tab("My direction").click();
  await shot("direction");
  await tab("Today").click();
  await button("Explore nearby Optional places and events to practise.").click();
  await shot("events");
  await button("Set up nearby opportunities").click();
  await page.getByText("No approved event sources are available yet. You can continue with everyday guidance.", { exact: true }).waitFor();
  await page.getByRole("textbox", { name: "Available days and times", exact: true }).fill("Weekends only");
  await button("Back").click();
  await button("Keep editing").click();
  assert.equal(await page.getByRole("textbox", { name: "Available days and times", exact: true }).inputValue(), "Weekends only");
  await button("Back").click();
  await button("Discard changes").click();
  await button("Set up nearby opportunities").waitFor();
  await button("Back").click();
  await page.goto("http://127.0.0.1:4173?voice");
  await tab("Journal").click();
  await shot("journal-mobile");
  await button("Talk it through Record, review the transcript, then share it.").click();
  await button("Start recording").waitFor();
  await shot("voice-intro");
  await button("Back").click();
  await button("Stay here").click();
  await button("Start recording").waitFor();
  await button("Back").click();
  await button("Leave").click();
  await page.goto("http://127.0.0.1:4173?event");
  await button("Explore nearby Optional places and events to practise.").click();
  await button("Use this as my next step").waitFor();
  await shot("event-match");
  for (const reason of ["Too much right now", "Not relevant", "Too far", "Bad timing", "Wrong type of event", "This event is stale or incorrect"]) {
    await button("Not for me").click();
    await button(reason).click();
    assert.equal(await button("Use this as my next step").count(), 0);
    await button("Find a suitable opportunity").click();
    await button("Use this as my next step").waitFor();
  }
  await button("Use this as my next step").click();
  await button("Cancel").click();
  await button("Use this as my next step").click();
  await button("Confirm change").click();
  assert.equal(await button("Use this as my next step").count(), 0);
  await page.goto("http://127.0.0.1:4173?empty");
  await button("Find my next step").waitFor();
  await shot("empty");
  await tab("Journal").click();
  await page.getByText("Your story starts here", { exact: true }).waitFor();
  await page.goto("http://127.0.0.1:4173?lang=it");
  await page.getByText("Un piccolo passo avanti.", { exact: true }).waitFor();
  await shot("italian");
  await page.setViewportSize({ width: 320, height: 640 });
  await shot("small-phone");
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.goto("http://127.0.0.1:4173?failure");
  await button("Close").scrollIntoViewIfNeeded();
  await shot("load-error");
  await button("Retry loading activity").click();
  await page.getByText("A little forward.", { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log("PASS: focused navigation, draft keep/discard, journal submission, three-stage report/back, change review, preference back/keep/discard, all event rejection reasons and acceptance/cancel, voice introduction/leave, empty states, Italian, 320px layout, failed-load recovery; screenshots saved.");
} finally { await browser.close(); }
