export const EULA = `
Apps made available through the App Store are licensed, not sold, to you. Your license to each App is subject to your prior acceptance of either this Licensed Application End User License Agreement (“Standard EULA”), or a custom end user license agreement between you and the Application Provider (“Custom EULA”), if one is provided. Your license to any Apple App under this Standard EULA or Custom EULA is granted by Apple, and your license to any Third Party App under this Standard EULA or Custom EULA is granted by the Application Provider of that Third Party App. Any App that is subject to this Standard EULA is referred to herein as the “Licensed Application.” The Application Provider or Apple as applicable (“Licensor”) reserves all rights in and to the Licensed Application not expressly granted to you under this Standard EULA.

a. Scope of License: Licensor grants to you a nontransferable license to use the Licensed Application on any Apple-branded products that you own or control and as permitted by the Usage Rules. The terms of this Standard EULA will govern any content, materials, or services accessible from or purchased within the Licensed Application as well as upgrades provided by Licensor that replace or supplement the original Licensed Application, unless such upgrade is accompanied by a Custom EULA. Except as provided in the Usage Rules, you may not distribute or make the Licensed Application available over a network where it could be used by multiple devices at the same time. You may not transfer, redistribute or sublicense the Licensed Application and, if you sell your Apple Device to a third party, you must remove the Licensed Application from the Apple Device before doing so. You may not copy (except as permitted by this license and the Usage Rules), reverse-engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Licensed Application, any updates, or any part thereof (except as and only to the extent that any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open-sourced components included with the Licensed Application).

b. Consent to Use of Data: You agree that Licensor may collect and use technical data and related information—including but not limited to technical information about your device, system and application software, and peripherals—that is gathered periodically to facilitate the provision of software updates, product support, and other services to you (if any) related to the Licensed Application. Licensor may use this information, as long as it is in a form that does not personally identify you, to improve its products or to provide services or technologies to you.

c. Termination. This Standard EULA is effective until terminated by you or Licensor. Your rights under this Standard EULA will terminate automatically if you fail to comply with any of its terms. 

d. External Services. The Licensed Application may enable access to Licensor’s and/or third-party services and websites (collectively and individually, "External Services"). You agree to use the External Services at your sole risk. Licensor is not responsible for examining or evaluating the content or accuracy of any third-party External Services, and shall not be liable for any such third-party External Services. Data displayed by any Licensed Application or External Service, including but not limited to financial, medical and location information, is for general informational purposes only and is not guaranteed by Licensor or its agents. You will not use the External Services in any manner that is inconsistent with the terms of this Standard EULA or that infringes the intellectual property rights of Licensor or any third party. You agree not to use the External Services to harass, abuse, stalk, threaten or defame any person or entity, and that Licensor is not responsible for any such use. External Services may not be available in all languages or in your Home Country, and may not be appropriate or available for use in any particular location. To the extent you choose to use such External Services, you are solely responsible for compliance with any applicable laws. Licensor reserves the right to change, suspend, remove, disable or impose access restrictions or limits on any External Services at any time without notice or liability to you. 

e. NO WARRANTY: YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE LICENSED APPLICATION IS AT YOUR SOLE RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED APPLICATION AND ANY SERVICES PERFORMED OR PROVIDED BY THE LICENSED APPLICATION ARE PROVIDED "AS IS" AND “AS AVAILABLE,” WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE LICENSED APPLICATION AND ANY SERVICES, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, AND OF NONINFRINGEMENT OF THIRD-PARTY RIGHTS. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY LICENSOR OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. SHOULD THE LICENSED APPLICATION OR SERVICES PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.

f. Limitation of Liability. TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT SHALL LICENSOR BE LIABLE FOR PERSONAL INJURY OR ANY INCIDENTAL, SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE LICENSED APPLICATION, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, OR OTHERWISE) AND EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event shall Licensor’s total liability to you for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount of fifty dollars ($50.00). The foregoing limitations will apply even if the above stated remedy fails of its essential purpose.

g. You may not use or otherwise export or re-export the Licensed Application except as authorized by United States law and the laws of the jurisdiction in which the Licensed Application was obtained. In particular, but without limitation, the Licensed Application may not be exported or re-exported (a) into any U.S.-embargoed countries or (b) to anyone on the U.S. Treasury Department's Specially Designated Nationals List or the U.S. Department of Commerce Denied Persons List or Entity List. By using the Licensed Application, you represent and warrant that you are not located in any such country or on any such list. You also agree that you will not use these products for any purposes prohibited by United States law, including, without limitation, the development, design, manufacture, or production of nuclear, missile, or chemical or biological weapons.

h. The Licensed Application and related documentation are "Commercial Items", as that term is defined at 48 C.F.R. §2.101, consisting of "Commercial Computer Software" and "Commercial Computer Software Documentation", as such terms are used in 48 C.F.R. §12.212 or 48 C.F.R. §227.7202, as applicable. Consistent with 48 C.F.R. §12.212 or 48 C.F.R. §227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to U.S. Government end users (a) only as Commercial Items and (b) with only those rights as are granted to all other end users pursuant to the terms and conditions herein. Unpublished-rights reserved under the copyright laws of the United States.

i. Except to the extent expressly provided in the following paragraph, this Agreement and the relationship between you and Apple shall be governed by the laws of the State of California, excluding its conflicts of law provisions. You and Apple agree to submit to the personal and exclusive jurisdiction of the courts located within the county of Santa Clara, California, to resolve any dispute or claim arising from this Agreement. If (a) you are not a U.S. citizen; (b) you do not reside in the U.S.; (c) you are not accessing the Service from the U.S.; and (d) you are a citizen of one of the countries identified below, you hereby agree that any dispute or claim arising from this Agreement shall be governed by the applicable law set forth below, without regard to any conflict of law provisions, and you hereby irrevocably submit to the non-exclusive jurisdiction of the courts located in the state, province or country identified below whose law governs:

j. WE DO NOT TOLERATE OBJECTIONABLE CONTENT OR ABUSIVE USERS. YOU AGREE NOT TO POST ANY CONTENT THAT IS OFFENSIVE, DEFAMATORY, PORNOGRAPHIC, HARASSING, OR OTHERWISE INAPPROPRIATE. USERS CAN REPORT CONTENT, AND WE RESERVE THE RIGHT TO REMOVE ANY CONTENT OR USERS WHO VIOLATE THESE TERMS.

If you are a citizen of any European Union country or Switzerland, Norway or Iceland, the governing law and forum shall be the laws and courts of your usual place of residence.

Specifically excluded from application to this Agreement is that law known as the United Nations Convention on the International Sale of Goods.
`;

export const EULA_IT = `
Le app rese disponibili tramite l'App Store sono concesse in licenza, non vendute, a te. La tua licenza per ogni app è soggetta alla tua previa accettazione del presente Contratto di licenza per l'utente finale dell'applicazione con licenza ("EULA standard") o di un contratto di licenza per l'utente finale personalizzato tra te e il fornitore dell'applicazione ("EULA personalizzato"), se fornito. La tua licenza per qualsiasi app Apple ai sensi del presente EULA standard o EULA personalizzato è concessa da Apple e la tua licenza per qualsiasi app di terze parti ai sensi del presente EULA standard o EULA personalizzato è concessa dal fornitore dell'applicazione di tale app di terze parti. Qualsiasi app soggetta al presente EULA standard è qui definita "applicazione con licenza". Il fornitore dell'applicazione o Apple, a seconda dei casi ("licenziante") si riserva tutti i diritti sull'applicazione con licenza non espressamente concessi a te ai sensi del presente EULA standard.

a. Ambito di licenza: il Licenziante ti concede una licenza non trasferibile per utilizzare l'Applicazione con licenza su qualsiasi prodotto a marchio Apple di tua proprietà o controllo e come consentito dalle Regole di utilizzo. I termini di questo EULA standard regoleranno qualsiasi contenuto, materiale o servizio accessibile da o acquistato all'interno dell'Applicazione con licenza, nonché gli aggiornamenti forniti dal Licenziante che sostituiscono o integrano l'Applicazione con licenza originale, a meno che tale aggiornamento non sia accompagnato da un EULA personalizzato. Salvo quanto previsto nelle Regole di utilizzo, non puoi distribuire o rendere disponibile l'Applicazione con licenza su una rete in cui potrebbe essere utilizzata da più dispositivi contemporaneamente. Non puoi trasferire, ridistribuire o concedere in sublicenza l'Applicazione con licenza e, se vendi il tuo Dispositivo Apple a terzi, devi rimuovere l'Applicazione con licenza dal Dispositivo Apple prima di farlo. Non è consentito copiare (salvo quanto consentito dalla presente licenza e dalle Regole d'uso), effettuare operazioni di reverse engineering, disassemblare, tentare di ricavare il codice sorgente, modificare o creare lavori derivati ​​dell'Applicazione concessa in licenza, di eventuali aggiornamenti o di qualsiasi parte di essi (salvo e solo nella misura in cui una qualsiasi delle suddette restrizioni sia vietata dalla legge applicabile o nella misura in cui sia consentito dai termini di licenza che regolano l'uso di qualsiasi componente open source incluso nell'Applicazione concessa in licenza).

b. Consenso all'uso dei dati: accetti che il Licenziante possa raccogliere e utilizzare dati tecnici e informazioni correlate, incluse ma non limitate a informazioni tecniche sul tuo dispositivo, sistema e software applicativo e periferiche, che vengono raccolte periodicamente per facilitare la fornitura di aggiornamenti software, supporto prodotto e altri servizi a te (se presenti) correlati all'Applicazione con licenza. Il Licenziante può utilizzare queste informazioni, purché siano in una forma che non ti identifichi personalmente, per migliorare i suoi prodotti o per fornirti servizi o tecnologie.

c. Risoluzione. Il presente Contratto di licenza per l'utente finale standard è valido fino alla risoluzione da parte tua o del Licenziante. I tuoi diritti ai sensi del presente Contratto di licenza per l'utente finale standard cesseranno automaticamente se non rispetti uno qualsiasi dei suoi termini. 

d. Servizi esterni. L'Applicazione con licenza può consentire l'accesso ai servizi e ai siti Web del Licenziante e/o di terze parti (collettivamente e individualmente, "Servizi esterni"). Accetti di utilizzare i Servizi esterni a tuo esclusivo rischio. Il Licenziante non è responsabile dell'esame o della valutazione del contenuto o dell'accuratezza di Servizi esterni di terze parti e non sarà responsabile per tali Servizi esterni di terze parti. I dati visualizzati da qualsiasi Applicazione con licenza o Servizio esterno, inclusi ma non limitati a informazioni finanziarie, mediche e sulla posizione, sono solo a scopo informativo generale e non sono garantiti dal Licenziante o dai suoi agenti. Non utilizzerai i Servizi esterni in alcun modo che sia incoerente con i termini del presente EULA standard o che violi i diritti di proprietà intellettuale del Licenziante o di terze parti. Accetti di non utilizzare i Servizi esterni per molestare, abusare, perseguitare, minacciare o diffamare alcuna persona o entità e che il Licenziante non è responsabile di tale utilizzo. I Servizi esterni potrebbero non essere disponibili in tutte le lingue o nel tuo Paese di residenza e potrebbero non essere appropriati o disponibili per l'uso in una particolare posizione. Nella misura in cui scegli di utilizzare tali Servizi Esterni, sei il solo responsabile della conformità a qualsiasi legge applicabile. Il Licenziante si riserva il diritto di modificare, sospendere, rimuovere, disabilitare o imporre restrizioni o limiti di accesso a qualsiasi Servizio Esterno in qualsiasi momento senza preavviso o responsabilità nei tuoi confronti. 

e. NESSUNA GARANZIA: L'UTENTE RICONOSCE E ACCETTA ESPRESSAMENTE CHE L'USO DELL'APPLICAZIONE CONCESSA IN LICENZA AVVIENE A SUO ESCLUSIVO RISCHIO. NELLA MISURA MASSIMA CONSENTITA DALLA LEGGE APPLICABILE, L'APPLICAZIONE CON LICENZA E TUTTI I SERVIZI ESEGUITI O FORNITI DALL'APPLICAZIONE CON LICENZA SONO FORNITI "COSÌ COME SONO" E "COME DISPONIBILI", CON TUTTI I DIFETTI E SENZA GARANZIA DI ALCUN TIPO, E IL CONCENDENTE CON LA PRESENTE DECLINA OGNI GARANZIA E CONDIZIONE RELATIVAMENTE ALL'APPLICAZIONE CON LICENZA E A QUALSIASI SERVIZIO, SIA ESPRESSA, IMPLICITA O STATUTARIA, COMPRESE, SENZA LIMITAZIONI, LE GARANZIE E/O LE CONDIZIONI IMPLICITE DI COMMERCIABILITÀ, DI QUALITÀ SODDISFACENTE, DI IDONEITÀ PER UNO SCOPO PARTICOLARE, DI ACCURATEZZA, DI PACIFICO GODIMENTO E DI NON VIOLAZIONE DEI DIRITTI DI TERZI. NESSUNA INFORMAZIONE O CONSIGLIO ORALE O SCRITTO FORNITO DAL CONCENDENTE O DAL SUO RAPPRESENTANTE AUTORIZZATO COSTITUIRÀ UNA GARANZIA. QUALORA L'APPLICAZIONE O I SERVIZI CONCESSI IN LICENZA SI RIVELANO DIFETTOSI, L'UTENTE SI ASSUME L'INTERO COSTO DI TUTTI I SERVIZI, LE RIPARAZIONI O LE CORREZIONI NECESSARIE. ALCUNE GIURISDIZIONI NON CONSENTONO L'ESCLUSIONE DI GARANZIE IMPLICITE O LIMITAZIONI SUI DIRITTI STATUTARI APPLICABILI DI UN CONSUMATORE, PERTANTO LE ESCLUSIONI E LE LIMITAZIONI DI CUI SOPRA POTREBBERO NON ESSERE APPLICABILI.

f. Limitazione di responsabilità. NELLA MISURA NON PROIBITA DALLA LEGGE, IN NESSUN CASO IL CONCENDENTE SARÀ RESPONSABILE PER LESIONI PERSONALI O QUALSIASI DANNO ACCIDENTALE, SPECIALE, INDIRETTO O CONSEGUENTE, INCLUSI, SENZA LIMITAZIONE, DANNI PER PERDITA DI PROFITTI, PERDITA DI DATI, INTERRUZIONE DELL'ATTIVITÀ O QUALSIASI ALTRO DANNO O PERDITA COMMERCIALE, DERIVANTE DA O CORRELATO AL TUO UTILIZZO O ALL'IMPOSSIBILITÀ DI UTILIZZARE L'APPLICAZIONE CONCESSA IN LICENZA, COMUNQUE CAUSATA, INDIPENDENTEMENTE DALLA TEORIA DI RESPONSABILITÀ (CONTRATTO, ILLECITO CIVILE O ALTRO) E ANCHE SE IL CONCENDENTE È STATO INFORMATO DELLA POSSIBILITÀ DI TALI DANNI. ALCUNE GIURISDIZIONI NON CONSENTONO LA LIMITAZIONE DI RESPONSABILITÀ PER LESIONI PERSONALI O PER DANNI ACCIDENTALI O CONSEGUENTI, PERTANTO QUESTA LIMITAZIONE POTREBBE NON ESSERE APPLICABILE A VOI. In nessun caso la responsabilità totale del Licenziante nei vostri confronti per tutti i danni (salvo quanto richiesto dalla legge applicabile in casi che coinvolgono lesioni personali) supererà l'importo di cinquanta dollari ($ 50,00). Le limitazioni di cui sopra si applicheranno anche se il rimedio sopra indicato non raggiunge il suo scopo essenziale.

g. Non puoi utilizzare o altrimenti esportare o riesportare l'Applicazione con licenza, salvo quanto autorizzato dalla legge degli Stati Uniti e dalle leggi della giurisdizione in cui è stata ottenuta l'Applicazione con licenza. In particolare, ma senza limitazioni, l'Applicazione con licenza non può essere esportata o riesportata (a) in alcun paese sottoposto a embargo da parte degli Stati Uniti o (b) a chiunque sia presente nell'elenco dei cittadini appositamente designati del Dipartimento del Tesoro degli Stati Uniti o nell'elenco delle persone o delle entità vietate del Dipartimento del Commercio degli Stati Uniti. Utilizzando l'Applicazione con licenza, dichiari e garantisci di non trovarti in nessuno di tali paesi o di non essere presente in nessuno di tali elenchi. Accetti inoltre di non utilizzare questi prodotti per scopi proibiti dalla legge degli Stati Uniti, inclusi, senza limitazioni, lo sviluppo, la progettazione, la fabbricazione o la produzione di armi nucleari, missilistiche, chimiche o biologiche.

h. L'Applicazione con licenza e la relativa documentazione sono "Articoli commerciali", come definito in 48 CFR §2.101, costituiti da "Software per computer commerciale" e "Documentazione software per computer commerciale", come tali termini sono utilizzati in 48 CFR §12.212 o 48 CFR §227.7202, come applicabile. In conformità con 48 CFR §12.212 o 48 CFR §227.7202-1 fino a 227.7202-4, come applicabile, il Software per computer commerciale e la Documentazione software per computer commerciale vengono concessi in licenza agli utenti finali del governo degli Stati Uniti (a) solo come Articoli commerciali e (b) solo con quei diritti che sono concessi a tutti gli altri utenti finali ai sensi dei termini e delle condizioni qui contenuti. Diritti non pubblicati riservati ai sensi delle leggi sul copyright degli Stati Uniti.

i. Salvo quanto espressamente previsto nel paragrafo seguente, il presente Contratto e il rapporto tra te e Apple saranno disciplinati dalle leggi dello Stato della California, escluse le disposizioni sui conflitti di legge. Tu e Apple accettate di sottoporvi alla giurisdizione personale ed esclusiva dei tribunali situati nella contea di Santa Clara, California, per risolvere qualsiasi controversia o reclamo derivante dal presente Contratto. Se (a) non sei un cittadino statunitense; (b) non risiedi negli Stati Uniti; (c) non stai accedendo al Servizio dagli Stati Uniti; e (d) sei un cittadino di uno dei paesi identificati di seguito, accetti con la presente che qualsiasi controversia o reclamo derivante dal presente Contratto sarà disciplinato dalla legge applicabile di seguito indicata, senza riguardo a qualsiasi disposizione sui conflitti di legge, e con la presente ti sottoponi irrevocabilmente alla giurisdizione non esclusiva dei tribunali situati nello stato, provincia o paese identificati di seguito la cui legge disciplina:

j. NON TOLLERIAMO CONTENUTI DISCUTIBILI O UTENTI ABUSIVI. L'UTENTE ACCETTA DI NON PUBBLICARE CONTENUTI OFFENSIVI, DIFFAMATORI, PORNOGRAFICI, MOLESTI O ALTRIMENTI INAPPROPRIATI. GLI UTENTI POSSONO SEGNALARE I CONTENUTI E NOI CI RISERVIAMO IL DIRITTO DI RIMUOVERE QUALSIASI CONTENUTO O UTENTE CHE VIOLI QUESTI TERMINI.

Se sei cittadino di un paese dell'Unione Europea o della Svizzera, della Norvegia o dell'Islanda, la legge applicabile e il foro competente saranno le leggi e i tribunali del tuo luogo di residenza abituale.

È espressamente esclusa dall'applicazione al presente Contratto la legge nota come Convenzione delle Nazioni Unite sulla vendita internazionale di merci.
`