-- Esplora: content library of short reflective pieces.
--
-- Authoring shape for `cards` (jsonb array of card objects):
--   [
--     { "type": "text", "body": "..." },
--     { "type": "text", "body": "...", "link": { "url": "https://...", "label": "Read more" } },
--     { "type": "youtube", "video_id": "dQw4w9WgXcQ", "caption": "optional" },
--     { "type": "link", "url": "https://...", "label": "APA on anxiety", "description": "optional" }
--   ]

CREATE TYPE "public"."content_category" AS ENUM (
  'fear',
  'vulnerability',
  'connection',
  'stories',
  'science',
  'practice'
);

CREATE TABLE IF NOT EXISTS "public"."content_pieces" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "category" public.content_category NOT NULL,
  "hook" text NOT NULL,
  "cards" jsonb NOT NULL,
  "cover_image_path" text,
  "is_featured" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "content_pieces_cards_is_array"
    CHECK (jsonb_typeof(cards) = 'array')
);

CREATE INDEX IF NOT EXISTS "content_pieces_category_idx"
  ON "public"."content_pieces" (category, created_at DESC);

-- Enforce at most one featured piece at a time.
CREATE UNIQUE INDEX IF NOT EXISTS "content_pieces_single_featured_idx"
  ON "public"."content_pieces" ((1)) WHERE is_featured;

ALTER TABLE "public"."content_pieces" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Pieces readable by authenticated users"
  ON "public"."content_pieces";
CREATE POLICY "Pieces readable by authenticated users"
  ON "public"."content_pieces" FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Admins can manage pieces"
  ON "public"."content_pieces";
CREATE POLICY "Admins can manage pieces"
  ON "public"."content_pieces" FOR ALL
  TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true));

CREATE TABLE IF NOT EXISTS "public"."content_bookmarks" (
  "user_id" uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  "piece_id" bigint NOT NULL REFERENCES public.content_pieces(id) ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id", "piece_id")
);

CREATE INDEX IF NOT EXISTS "content_bookmarks_user_idx"
  ON "public"."content_bookmarks" (user_id, created_at DESC);

ALTER TABLE "public"."content_bookmarks" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage their own bookmarks"
  ON "public"."content_bookmarks";
CREATE POLICY "Users manage their own bookmarks"
  ON "public"."content_bookmarks" FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
