-- Generated from scripts/side-quests/review/output/reviews/default.json
-- Applies rewrite notes for quests that were kept but marked with follow-up edits.

BEGIN;

DO $migration$
DECLARE
  quest_ids bigint[] := ARRAY[
    10, 20, 22, 35, 47, 52, 97, 131, 133, 152, 175, 186, 192, 193,
    202, 203, 209, 211, 212, 213, 215, 235, 254, 300, 303, 313, 314, 315
  ]::bigint[];
  expected_count integer := 28;
  matched_count integer;
  updated_count integer;
BEGIN
  SELECT count(*)
  INTO matched_count
  FROM public.side_quests
  WHERE id = ANY (quest_ids);

  IF matched_count <> expected_count THEN
    RAISE EXCEPTION 'Expected % reviewed side quests to exist, found %', expected_count, matched_count;
  END IF;

  WITH updates (
    id,
    title,
    summary,
    goal_tags,
    barrier_tags,
    context_tags,
    type_tags,
    outcome_tags,
    stretch_level,
    cost_level,
    planning_level,
    social_level,
    physical_level,
    distance_level,
    night_level,
    avoid_flags
  ) AS (
    VALUES
      (
        10::bigint,
        $$Disegna una mini-mappa del tuo quartiere$$,
        $$Disegna una mini mappa del tuo quartiere o della tua zona come se dovessi orientare qualcuno che arriva da fuori. Segna su un foglio tre luoghi che contano per te, aggiungi indicazioni semplici o piccoli riferimenti e tienila per te o appendila dove la rivedrai.$$,
        ARRAY['novelty', 'creativity', 'better_stories']::text[],
        ARRAY['overthinking']::text[],
        ARRAY['at_home', 'near_home', 'solo']::text[],
        ARRAY['creative', 'exploratory', 'reflective']::text[],
        ARRAY['explored_more', 'days_less_repetitive', 'more_stories']::text[],
        'easy_win',
        0,
        0,
        0,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        20::bigint,
        $$Fai una performance di novanta secondi a un open mic$$,
        $$Porta una micro-performance dal vivo davanti a un piccolo pubblico, in un open mic, un circolo o un bar con serata libera. Cerca un evento per stasera, prepara novanta secondi di storia, poesia o canzone, chiedi un posto in lista e sali al microfono senza superare il tempo.$$,
        ARRAY['novelty', 'better_stories', 'connection']::text[],
        ARRAY['feeling_self_conscious', 'social_hesitation']::text[],
        ARRAY['out_in_the_city', 'with_other_people']::text[],
        ARRAY['social', 'creative', 'growth_edge']::text[],
        ARRAY['did_something_unusual', 'more_stories', 'felt_more_alive']::text[],
        'bold_nudge',
        1,
        1,
        3,
        0,
        2,
        1,
        ARRAY['talking_to_strangers', 'group_social_situations', 'nighttime']::text[]
      ),
      (
        22::bigint,
        $$Crea una mini-zine di una pagina$$,
        $$Crea una mini-zine di una pagina su una tua ossessione innocua o su una cosa che ti diverte davvero. Piega un A4 in otto riquadri, riempilo con titolo, disegni e tre brevi testi, poi tienilo per te o fanne qualche copia se ti va.$$,
        ARRAY['creativity', 'novelty', 'better_stories']::text[],
        ARRAY['overthinking', 'feeling_self_conscious']::text[],
        ARRAY['at_home', 'solo']::text[],
        ARRAY['creative', 'reflective']::text[],
        ARRAY['did_something_unusual', 'more_stories', 'days_less_repetitive']::text[],
        'moderate_push',
        0,
        1,
        0,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        35::bigint,
        $$Offriti di portare a spasso il cane di qualcuno$$,
        $$Offriti di portare a spasso il cane di qualcuno che conosci o di una persona del quartiere che ha bisogno di una mano. Chiedi se puoi occupartene per un giro semplice, segui le indicazioni su guinzaglio e percorso e fai la passeggiata senza trasformarla in un favore enorme.$$,
        ARRAY['connection', 'better_stories', 'momentum']::text[],
        ARRAY['overthinking', 'social_hesitation']::text[],
        ARRAY['near_home', 'out_in_the_city', 'with_other_people']::text[],
        ARRAY['social', 'growth_edge', 'exploratory']::text[],
        ARRAY['shared_more_with_people', 'more_stories', 'felt_more_alive']::text[],
        'moderate_push',
        0,
        1,
        2,
        2,
        1,
        0,
        ARRAY[]::text[]
      ),
      (
        47::bigint,
        $$Costruisci qualcosa in un fablab$$,
        $$Vai in un fablab, makerspace o laboratorio aperto e realizza un oggetto semplice con gli strumenti del posto. Chiedi quale progetto base puoi fare oggi, fatti spiegare il passaggio tecnico principale e porta a casa quello che riesci a costruire.$$,
        ARRAY['novelty', 'creativity', 'better_stories']::text[],
        ARRAY['not_knowing']::text[],
        ARRAY['out_in_the_city', 'with_other_people', 'solo']::text[],
        ARRAY['creative', 'exploratory', 'growth_edge']::text[],
        ARRAY['did_something_unusual', 'more_stories', 'felt_more_alive']::text[],
        'moderate_push',
        2,
        2,
        2,
        1,
        2,
        0,
        ARRAY['spending_money', 'talking_to_strangers']::text[]
      ),
      (
        52::bigint,
        $$Pulisci un parco, una spiaggia o un argine$$,
        $$Dedica un'uscita a ripulire un pezzo di parco, spiaggia, argine o sentiero che ti sembra trascurato. Porta con te un sacco e dei guanti robusti, raccogli quello che riesci in modo sicuro e smetti quando hai riempito almeno un sacchetto o migliorato chiaramente l'area.$$,
        ARRAY['momentum', 'better_stories', 'novelty']::text[],
        ARRAY['overthinking']::text[],
        ARRAY['near_home', 'out_in_the_city', 'solo']::text[],
        ARRAY['exploratory', 'growth_edge']::text[],
        ARRAY['did_something_unusual', 'explored_more', 'felt_more_alive']::text[],
        'moderate_push',
        0,
        0,
        0,
        2,
        1,
        0,
        ARRAY[]::text[]
      ),
      (
        97::bigint,
        $$Crea una capsula del tempo$$,
        $$Crea una capsula del tempo per una versione futura di te o per una giornata che vuoi ricordare meglio. Metti in una scatola o in una busta un piccolo oggetto, una frase scritta e una data di riapertura, poi nascondila in un posto sicuro e non toccarla prima del momento scelto.$$,
        ARRAY['creativity', 'better_stories', 'momentum']::text[],
        ARRAY['overthinking']::text[],
        ARRAY['at_home', 'solo']::text[],
        ARRAY['creative', 'reflective']::text[],
        ARRAY['days_less_repetitive', 'more_stories', 'followed_impulses']::text[],
        'easy_win',
        0,
        0,
        0,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        131::bigint,
        $$Canta una canzone con amici da un balcone$$,
        $$Canta una canzone breve con amici da un balcone, in cortile o in un altro punto di casa che vi faccia un po’ ridere. Scegliete un brano o una filastrocca di massimo trenta secondi, fate una sola take senza ricominciare e lasciate che venga come viene.$$,
        ARRAY['fun', 'connection', 'creativity']::text[],
        ARRAY['overthinking']::text[],
        ARRAY['at_home', 'near_home', 'with_other_people']::text[],
        ARRAY['playful', 'creative', 'social']::text[],
        ARRAY['did_something_unusual', 'shared_more_with_people']::text[],
        'moderate_push',
        0,
        1,
        2,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        133::bigint,
        $$Chiedi a un fotografo di farti un ritratto$$,
        $$Chiedi a un fotografo che incontri in giro se può scattarti una foto usando il suo occhio invece del tuo. Avvicinati senza interrompere il lavoro, chiedi un solo ritratto veloce, fatti guidare per posa o luce e ringrazia davvero guardando il risultato.$$,
        ARRAY['novelty', 'connection', 'better_stories']::text[],
        ARRAY['social_hesitation', 'feeling_self_conscious']::text[],
        ARRAY['out_in_the_city', 'with_other_people', 'solo']::text[],
        ARRAY['social', 'growth_edge', 'creative']::text[],
        ARRAY['did_something_unusual', 'shared_more_with_people', 'more_stories']::text[],
        'bold_nudge',
        0,
        0,
        3,
        1,
        1,
        0,
        ARRAY['talking_to_strangers']::text[]
      ),
      (
        152::bigint,
        $$Scrivi una storia da tre parole date da uno sconosciuto$$,
        $$Scrivi una storia breve partendo da tre parole date da uno sconosciuto e tienila per te. Vai in un bar, in biblioteca o in un parco, chiedi tre parole a caso a una persona, poi usa quelle parole per comporre una pagina o qualche riga sul telefono.$$,
        ARRAY['creativity', 'better_stories', 'novelty']::text[],
        ARRAY['social_hesitation', 'overthinking']::text[],
        ARRAY['out_in_the_city', 'solo', 'with_other_people']::text[],
        ARRAY['creative', 'growth_edge', 'social']::text[],
        ARRAY['more_stories', 'did_something_unusual', 'followed_impulses']::text[],
        'moderate_push',
        0,
        0,
        2,
        0,
        1,
        0,
        ARRAY['talking_to_strangers']::text[]
      ),
      (
        175::bigint,
        $$Compra qualcosa per la persona dietro di te in fila$$,
        $$Quando sei in fila in un bar, in pasticceria, al supermercato o in un altro posto, offri una piccola cosa alla persona dietro di te. Scegli qualcosa di semplice e sostenibile per te, dillo alla cassa prima che paghi lei e consegnalo senza trasformarlo in una scena.$$,
        ARRAY['connection', 'better_stories', 'novelty']::text[],
        ARRAY['social_hesitation', 'spending_money']::text[],
        ARRAY['out_in_the_city', 'with_other_people']::text[],
        ARRAY['social', 'growth_edge']::text[],
        ARRAY['shared_more_with_people', 'more_stories', 'felt_more_alive']::text[],
        'moderate_push',
        1,
        0,
        2,
        1,
        1,
        0,
        ARRAY['spending_money', 'talking_to_strangers']::text[]
      ),
      (
        186::bigint,
        $$Chiedi a un bibliotecario un libro da leggere$$,
        $$Vai in biblioteca e fatti consigliare un libro da qualcuno che ci lavora invece di scegliere da solo. Dai qualche indizio su di te o sui tuoi gusti, accetta la raccomandazione senza contrattare e leggi almeno l'inizio di quello che ti suggerisce.$$,
        ARRAY['novelty', 'connection', 'better_stories']::text[],
        ARRAY['not_knowing', 'overthinking']::text[],
        ARRAY['out_in_the_city', 'with_other_people', 'solo']::text[],
        ARRAY['exploratory', 'social']::text[],
        ARRAY['explored_more', 'more_stories', 'did_something_unusual']::text[],
        'moderate_push',
        0,
        0,
        1,
        0,
        1,
        0,
        ARRAY['talking_to_strangers']::text[]
      ),
      (
        192::bigint,
        $$Chiedi a qualcuno in palestra come si fa il suo esercizio$$,
        $$In palestra o in un parco fitness chiedi a una persona come si esegue l'esercizio che sta facendo, se il momento e' adatto. Aspetta che finisca la serie, chiedi una spiegazione rapida o una dimostrazione e prova il movimento solo se ti senti al sicuro.$$,
        ARRAY['novelty', 'momentum', 'better_stories']::text[],
        ARRAY['feeling_self_conscious', 'social_hesitation']::text[],
        ARRAY['out_in_the_city', 'with_other_people']::text[],
        ARRAY['growth_edge', 'social']::text[],
        ARRAY['did_something_unusual', 'felt_more_alive']::text[],
        'moderate_push',
        1,
        0,
        2,
        2,
        1,
        0,
        ARRAY['talking_to_strangers']::text[]
      ),
      (
        193::bigint,
        $$Vai a una lezione di ballo$$,
        $$Vai a una lezione di ballo e lascia che il corpo impari qualcosa prima che la testa lo giudichi. Scegli una classe aperta ai principianti, presentati anche se non conosci nessuno e resta fino alla fine senza scusarti per gli errori.$$,
        ARRAY['novelty', 'connection', 'better_stories']::text[],
        ARRAY['social_hesitation', 'feeling_self_conscious']::text[],
        ARRAY['out_in_the_city', 'with_other_people']::text[],
        ARRAY['social', 'growth_edge', 'exploratory']::text[],
        ARRAY['did_something_unusual', 'felt_more_alive', 'more_stories']::text[],
        'moderate_push',
        1,
        1,
        2,
        2,
        1,
        0,
        ARRAY['talking_to_strangers', 'group_social_situations']::text[]
      ),
      (
        202::bigint,
        $$Vai con un amico in un negozio e sceglietevi un outfit$$,
        $$Vai con un amico in un negozio o in un thrift store e lasciate che sia l'altro a scegliere un outfit per te. Datevi un perimetro semplice, provate almeno un completo a testa e uscite dal camerino mostrando il risultato senza smontarlo subito.$$,
        ARRAY['novelty', 'fun', 'connection']::text[],
        ARRAY['feeling_self_conscious', 'social_hesitation']::text[],
        ARRAY['out_in_the_city', 'with_other_people']::text[],
        ARRAY['playful', 'social', 'growth_edge']::text[],
        ARRAY['did_something_unusual', 'shared_more_with_people', 'more_stories']::text[],
        'moderate_push',
        0,
        1,
        2,
        1,
        1,
        0,
        ARRAY[]::text[]
      ),
      (
        203::bigint,
        $$Vai a una degustazione di vini$$,
        $$Vai a una degustazione di vini o chiedi un piccolo assaggio guidato in enoteca senza fingere di saperne più di quello che sai. Ascolta la spiegazione, prova almeno due assaggi se disponibili e descrivi ad alta voce cosa noti davvero.$$,
        ARRAY['novelty', 'fun', 'better_stories']::text[],
        ARRAY['not_knowing']::text[],
        ARRAY['out_in_the_city', 'solo']::text[],
        ARRAY['exploratory', 'social']::text[],
        ARRAY['more_stories', 'explored_more']::text[],
        'moderate_push',
        2,
        0,
        1,
        0,
        1,
        0,
        ARRAY['spending_money', 'talking_to_strangers']::text[]
      ),
      (
        209::bigint,
        $$Vai a far volare un aquilone$$,
        $$Prendi un aquilone e vai in un posto aperto per farlo alzare anche se non ti viene subito bene. Cerca un parco o una spiaggia con abbastanza spazio, fai qualche tentativo senza scoraggiarti e fermati solo quando l’hai visto davvero prendere il vento.$$,
        ARRAY['novelty', 'fun', 'momentum']::text[],
        ARRAY['overthinking']::text[],
        ARRAY['out_in_the_city', 'solo']::text[],
        ARRAY['playful', 'exploratory']::text[],
        ARRAY['felt_more_alive', 'did_something_unusual', 'days_less_repetitive']::text[],
        'easy_win',
        1,
        1,
        0,
        1,
        1,
        0,
        ARRAY[]::text[]
      ),
      (
        211::bigint,
        $$Parla con una persona più anziana della sua infanzia$$,
        $$Fai una conversazione vera con una persona più anziana, che la conosca o no, chiedendole com’era la sua infanzia o la sua vita da giovane. Parti da una domanda semplice, ascolta senza portarti subito al centro e tieniti in mente almeno un dettaglio da raccontare dopo.$$,
        ARRAY['connection', 'better_stories', 'novelty']::text[],
        ARRAY['not_knowing', 'social_hesitation']::text[],
        ARRAY['near_home', 'out_in_the_city', 'with_other_people']::text[],
        ARRAY['social', 'reflective']::text[],
        ARRAY['shared_more_with_people', 'more_stories', 'felt_more_alive']::text[],
        'moderate_push',
        0,
        0,
        2,
        0,
        1,
        0,
        ARRAY[]::text[]
      ),
      (
        212::bigint,
        $$Compra una usa-e-getta e cerca cinque cose suggerite da sconosciuti$$,
        $$Compra una usa-e-getta o porta con te un rullino e chiedi a degli sconosciuti cinque cose da trovare e fotografare in città. Passa la giornata a cercarle una per una, scatta solo quando le trovi davvero e tieni insieme la serie come mappa del tuo giro.$$,
        ARRAY['novelty', 'creativity', 'better_stories']::text[],
        ARRAY['social_hesitation', 'not_knowing']::text[],
        ARRAY['out_in_the_city', 'solo', 'with_other_people']::text[],
        ARRAY['creative', 'exploratory', 'growth_edge']::text[],
        ARRAY['did_something_unusual', 'explored_more', 'more_stories']::text[],
        'bold_nudge',
        2,
        1,
        2,
        2,
        2,
        0,
        ARRAY['spending_money', 'talking_to_strangers']::text[]
      ),
      (
        213::bigint,
        $$Vai a uno scambio linguistico$$,
        $$Vai a uno scambio linguistico e resta lì abbastanza da parlare davvero con qualcuno. Presentati anche se sei impacciato, fai almeno una domanda nella lingua che studi e continua la conversazione senza passare subito all’italiano.$$,
        ARRAY['connection', 'novelty', 'better_stories']::text[],
        ARRAY['not_knowing', 'social_hesitation']::text[],
        ARRAY['out_in_the_city', 'with_other_people']::text[],
        ARRAY['social', 'growth_edge', 'exploratory']::text[],
        ARRAY['shared_more_with_people', 'explored_more', 'felt_more_alive']::text[],
        'bold_nudge',
        1,
        1,
        3,
        1,
        2,
        0,
        ARRAY['talking_to_strangers', 'group_social_situations']::text[]
      ),
      (
        215::bigint,
        $$Vai a una lezione o a un workshop di ceramica$$,
        $$Vai a una lezione o a un workshop di ceramica e lascia che le mani sbaglino davanti a qualcuno. Prova il tornio o una tecnica base, segui le indicazioni dell'insegnante e porta a termine un pezzo anche se viene storto.$$,
        ARRAY['novelty', 'creativity', 'better_stories']::text[],
        ARRAY['overthinking', 'feeling_self_conscious']::text[],
        ARRAY['out_in_the_city', 'with_other_people', 'solo']::text[],
        ARRAY['creative', 'growth_edge', 'exploratory']::text[],
        ARRAY['did_something_unusual', 'more_stories', 'felt_more_alive']::text[],
        'moderate_push',
        2,
        1,
        2,
        1,
        2,
        0,
        ARRAY['spending_money']::text[]
      ),
      (
        235::bigint,
        $$Fai la spesa chiedendo agli altri cosa comprare$$,
        $$Al supermercato o al mercato, ogni volta che devi scegliere qualcosa chiedi a una persona vicina quale prendere e accetta la risposta. Fallo per alcuni acquisti reali, come una verdura, uno snack o un formato di pasta, e porta a casa almeno tre scelte che non avresti fatto da solo.$$,
        ARRAY['connection', 'novelty', 'better_stories']::text[],
        ARRAY['social_hesitation', 'overthinking']::text[],
        ARRAY['out_in_the_city', 'solo', 'with_other_people']::text[],
        ARRAY['social', 'exploratory', 'growth_edge']::text[],
        ARRAY['did_something_unusual', 'explored_more', 'more_stories']::text[],
        'bold_nudge',
        2,
        0,
        3,
        1,
        1,
        0,
        ARRAY['talking_to_strangers']::text[]
      ),
      (
        254::bigint,
        $$Scrivi un messaggio e lascialo in un posto pubblico$$,
        $$Scrivi un messaggio, una nota o una piccola lettera su qualcosa che ti va di dire e lascialo in un posto pubblico dove qualcuno possa trovarlo. Scegli un punto adatto e rispettoso, scrivi in modo leggibile e vai via senza controllare chi lo prenderà.$$,
        ARRAY['creativity', 'better_stories', 'connection']::text[],
        ARRAY['feeling_self_conscious', 'overthinking']::text[],
        ARRAY['out_in_the_city', 'solo']::text[],
        ARRAY['creative', 'growth_edge', 'reflective']::text[],
        ARRAY['did_something_unusual', 'more_stories', 'followed_impulses']::text[],
        'moderate_push',
        0,
        0,
        0,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        300::bigint,
        $$Scrivi una lettera al tuo io futuro e sigillala$$,
        $$Scrivi una lettera a una versione futura di te e chiudila finché non sarà il momento di riaprirla. Prendi un foglio, scrivi qualche riga onesta su come stai e scegli una data abbastanza lontana, come tra un anno o più.$$,
        ARRAY['creativity', 'momentum']::text[],
        ARRAY['low_energy', 'overthinking']::text[],
        ARRAY['at_home', 'solo']::text[],
        ARRAY['creative', 'reflective']::text[],
        ARRAY['followed_impulses']::text[],
        'easy_win',
        0,
        0,
        0,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        303::bigint,
        $$Disegna la vista dalla tua finestra$$,
        $$Disegna la vista dalla tua finestra senza darti un tempo minimo da rispettare. Prendi carta e una matita qualsiasi, schizza ciò che vedi con calma e fermati quando senti di aver davvero guardato il posto in cui sei.$$,
        ARRAY['creativity', 'momentum']::text[],
        ARRAY['low_energy', 'overthinking']::text[],
        ARRAY['at_home', 'solo']::text[],
        ARRAY['creative', 'reflective']::text[],
        ARRAY['followed_impulses']::text[],
        'easy_win',
        0,
        0,
        0,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        313::bigint,
        $$Raccogli ricette di famiglia e mettile insieme$$,
        $$Raccogli alcune ricette di famiglia e inizia a metterle insieme in un piccolo quaderno o file tutto tuo. Chiedi ingredienti e procedimento a parenti o persone vicine, trascrivi quello che ricevi e organizza le ricette in modo che restino.$$,
        ARRAY['connection', 'creativity', 'better_stories']::text[],
        ARRAY['not_knowing']::text[],
        ARRAY['at_home', 'solo', 'with_other_people']::text[],
        ARRAY['creative', 'social', 'reflective']::text[],
        ARRAY['more_stories', 'shared_more_with_people']::text[],
        'moderate_push',
        0,
        1,
        1,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        314::bigint,
        $$Impara a piegare un origami$$,
        $$Impara a piegare un origami semplice senza pretendere di saperlo fare a memoria. Scegli una figura, segui un tutorial passo dopo passo e ripeti finché ti esce almeno una versione di cui sei soddisfatto.$$,
        ARRAY['creativity', 'momentum', 'novelty']::text[],
        ARRAY['not_knowing', 'overthinking']::text[],
        ARRAY['at_home', 'solo']::text[],
        ARRAY['creative', 'reflective']::text[],
        ARRAY['followed_impulses', 'days_less_repetitive']::text[],
        'easy_win',
        0,
        0,
        0,
        0,
        0,
        0,
        ARRAY[]::text[]
      ),
      (
        315::bigint,
        $$Vai a una lettura dei tarocchi$$,
        $$Vai a una lettura dei tarocchi senza dover arrivare con una domanda perfetta o una tesi da difendere. Cerca una persona o un posto che ti ispiri abbastanza, presentati con curiosità e ascolta quello che emerge senza decidere subito cosa farne.$$,
        ARRAY['novelty', 'better_stories', 'creativity']::text[],
        ARRAY['not_knowing', 'overthinking']::text[],
        ARRAY['out_in_the_city', 'solo']::text[],
        ARRAY['exploratory', 'reflective', 'growth_edge']::text[],
        ARRAY['did_something_unusual', 'more_stories', 'felt_more_alive']::text[],
        'moderate_push',
        2,
        1,
        1,
        0,
        1,
        0,
        ARRAY['spending_money', 'talking_to_strangers']::text[]
      )
  )
  UPDATE public.side_quests AS sq
  SET
    title = updates.title,
    summary = updates.summary,
    goal_tags = updates.goal_tags,
    barrier_tags = updates.barrier_tags,
    context_tags = updates.context_tags,
    type_tags = updates.type_tags,
    outcome_tags = updates.outcome_tags,
    stretch_level = updates.stretch_level,
    cost_level = updates.cost_level,
    planning_level = updates.planning_level,
    social_level = updates.social_level,
    physical_level = updates.physical_level,
    distance_level = updates.distance_level,
    night_level = updates.night_level,
    avoid_flags = updates.avoid_flags,
    updated_at = now()
  FROM updates
  WHERE sq.id = updates.id;

  GET DIAGNOSTICS updated_count = ROW_COUNT;

  IF updated_count <> expected_count THEN
    RAISE EXCEPTION 'Expected % reviewed side quests to update, updated %', expected_count, updated_count;
  END IF;
END $migration$;

COMMIT;
