-- Esplora: content library of short reflective pieces
-- Categories are a fixed set of 6, enforced via CHECK constraint.

CREATE TABLE IF NOT EXISTS "public"."content_pieces" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "category" text NOT NULL,
  "hook" text NOT NULL,
  "cards" jsonb NOT NULL,
  "closing_kind" text NOT NULL,
  "closing_text" text NOT NULL,
  "closing_challenge_id" bigint,
  "external_link_url" text,
  "external_link_label" text,
  "cover_image_path" text,
  "linked_challenge_id" bigint,
  "is_published" boolean NOT NULL DEFAULT false,
  "is_featured" boolean NOT NULL DEFAULT false,
  "published_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "content_pieces_category_check"
    CHECK (category IN ('fear', 'vulnerability', 'connection', 'stories', 'science', 'practice')),
  CONSTRAINT "content_pieces_closing_kind_check"
    CHECK (closing_kind IN ('prompt', 'cta')),
  CONSTRAINT "content_pieces_cards_is_array"
    CHECK (jsonb_typeof(cards) = 'array'),
  CONSTRAINT "content_pieces_closing_challenge_fkey"
    FOREIGN KEY (closing_challenge_id) REFERENCES public.challenges(id) ON DELETE SET NULL,
  CONSTRAINT "content_pieces_linked_challenge_fkey"
    FOREIGN KEY (linked_challenge_id) REFERENCES public.challenges(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "content_pieces_published_idx"
  ON "public"."content_pieces" (is_published, published_at DESC);

CREATE INDEX IF NOT EXISTS "content_pieces_category_idx"
  ON "public"."content_pieces" (category, published_at DESC)
  WHERE is_published;

-- Enforce at most one featured piece at a time.
CREATE UNIQUE INDEX IF NOT EXISTS "content_pieces_single_featured_idx"
  ON "public"."content_pieces" ((1)) WHERE is_featured;

ALTER TABLE "public"."content_pieces" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Published pieces readable by authenticated users"
  ON "public"."content_pieces";
CREATE POLICY "Published pieces readable by authenticated users"
  ON "public"."content_pieces" FOR SELECT
  TO authenticated
  USING (is_published = true);

DROP POLICY IF EXISTS "Admins can manage pieces"
  ON "public"."content_pieces";
CREATE POLICY "Admins can manage pieces"
  ON "public"."content_pieces" FOR ALL
  TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND is_admin = true));

CREATE TABLE IF NOT EXISTS "public"."content_bookmarks" (
  "user_id" uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  "piece_id" bigint NOT NULL REFERENCES public.content_pieces(id) ON DELETE CASCADE,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("user_id", "piece_id")
);

CREATE INDEX IF NOT EXISTS "content_bookmarks_user_idx"
  ON "public"."content_bookmarks" (user_id, created_at DESC);

ALTER TABLE "public"."content_bookmarks" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage their own bookmarks"
  ON "public"."content_bookmarks";
CREATE POLICY "Users manage their own bookmarks"
  ON "public"."content_bookmarks" FOR ALL
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
