create table public.growth_intakes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  answers jsonb not null default '{}'::jsonb,
  status text not null default 'in_progress'
    check (status in ('in_progress', 'proposed', 'confirmed', 'abandoned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.growth_plans (
  id uuid primary key default gen_random_uuid(),
  intake_id uuid not null references public.growth_intakes(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete cascade,
  version integer not null check (version > 0),
  status text not null default 'proposed'
    check (status in ('proposed', 'active', 'rejected', 'superseded')),
  goal text not null check (char_length(goal) between 1 and 600),
  formulation text not null check (char_length(formulation) between 1 and 1000),
  milestones jsonb not null check (
    jsonb_typeof(milestones) = 'array'
    and jsonb_array_length(milestones) between 3 and 4
  ),
  current_focus text not null check (char_length(current_focus) between 1 and 500),
  first_step jsonb not null check (jsonb_typeof(first_step) = 'object'),
  model_name text not null,
  prompt_version text not null,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  unique (user_id, version)
);

create unique index growth_plans_one_active_per_user
  on public.growth_plans(user_id)
  where status = 'active';

create table public.growth_plan_evidence (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  intake_id uuid not null references public.growth_intakes(id) on delete restrict,
  plan_id uuid references public.growth_plans(id) on delete set null,
  kind text not null check (kind in ('correction', 'confirmation')),
  content jsonb not null,
  created_at timestamptz not null default now()
);

create table public.growth_event_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  intake_id uuid not null references public.growth_intakes(id) on delete cascade,
  enabled boolean not null default false,
  approximate_location text not null default '',
  travel_radius text not null default '',
  availability text not null default '',
  cost_preference text not null default '',
  accessibility_needs text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.growth_generation_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  intake_id uuid not null references public.growth_intakes(id) on delete cascade,
  request_fingerprint text not null,
  status text not null default 'started'
    check (status in ('started', 'completed', 'failed')),
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

create index growth_generation_requests_user_created_idx
  on public.growth_generation_requests(user_id, created_at desc);
create index growth_generation_requests_fingerprint_idx
  on public.growth_generation_requests(user_id, request_fingerprint, created_at desc);

alter table public.growth_intakes enable row level security;
alter table public.growth_plans enable row level security;
alter table public.growth_plan_evidence enable row level security;
alter table public.growth_event_preferences enable row level security;
alter table public.growth_generation_requests enable row level security;

create policy "Users can read own growth intakes"
  on public.growth_intakes for select
  using (auth.uid() = user_id);
create policy "Users can create own growth intakes"
  on public.growth_intakes for insert
  with check (auth.uid() = user_id);
create policy "Users can update own in-progress growth intakes"
  on public.growth_intakes for update
  using (auth.uid() = user_id and status = 'in_progress')
  with check (auth.uid() = user_id and status in ('in_progress', 'abandoned'));

create policy "Users can read own growth plans"
  on public.growth_plans for select
  using (auth.uid() = user_id);

create policy "Users can read own growth evidence"
  on public.growth_plan_evidence for select
  using (auth.uid() = user_id);

create policy "Users can read own growth event preferences"
  on public.growth_event_preferences for select
  using (auth.uid() = user_id);
create policy "Users can create own growth event preferences"
  on public.growth_event_preferences for insert
  with check (auth.uid() = user_id);
create policy "Users can update own growth event preferences"
  on public.growth_event_preferences for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy "Users can delete own growth event preferences"
  on public.growth_event_preferences for delete
  using (auth.uid() = user_id);

create policy "Users can read own growth generation requests"
  on public.growth_generation_requests for select
  using (auth.uid() = user_id);

create or replace function public.protect_growth_intake_evidence()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.user_id <> old.user_id or new.id <> old.id then
    raise exception 'Growth intake identity cannot be changed';
  end if;
  if old.status <> 'in_progress' and new.answers <> old.answers then
    raise exception 'Original growth intake evidence cannot be rewritten';
  end if;
  return new;
end;
$$;

create trigger protect_growth_intake_evidence_before_update
before update on public.growth_intakes
for each row execute function public.protect_growth_intake_evidence();

create or replace function public.persist_growth_plan_proposal(
  p_user_id uuid,
  p_intake_id uuid,
  p_goal text,
  p_formulation text,
  p_milestones jsonb,
  p_current_focus text,
  p_first_step jsonb,
  p_model_name text,
  p_prompt_version text,
  p_expected_answers jsonb,
  p_expected_event_preferences jsonb,
  p_previous_plan_id uuid default null,
  p_correction text default null
)
returns public.growth_plans
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_plan public.growth_plans;
  v_version integer;
  v_event_preferences jsonb;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  if p_previous_plan_id is null then
    perform 1 from public.growth_intakes
    where id = p_intake_id
      and user_id = p_user_id
      and status = 'in_progress'
      and answers = p_expected_answers
    for update;
    if not found then
      raise exception 'In-progress growth intake not found';
    end if;
  else
    perform 1
    from public.growth_intakes intake
    join public.growth_plans plan on plan.intake_id = intake.id
    where intake.id = p_intake_id
      and intake.user_id = p_user_id
      and intake.status = 'proposed'
      and intake.answers = p_expected_answers
      and plan.id = p_previous_plan_id
      and plan.user_id = p_user_id
      and plan.status = 'proposed'
    for update of intake, plan;
    if not found then
      raise exception 'Proposed growth plan transition is no longer valid';
    end if;
  end if;

  select jsonb_build_object(
    'enabled', enabled,
    'approximate_location', approximate_location,
    'travel_radius', travel_radius,
    'availability', availability,
    'cost_preference', cost_preference,
    'accessibility_needs', accessibility_needs
  )
  into v_event_preferences
  from public.growth_event_preferences
  where user_id = p_user_id and intake_id = p_intake_id
  for update;

  if v_event_preferences is distinct from p_expected_event_preferences then
    raise exception 'Growth guidance inputs changed during generation';
  end if;

  select coalesce(max(version), 0) + 1 into v_version
  from public.growth_plans where user_id = p_user_id;

  update public.growth_plans
  set status = 'rejected'
  where user_id = p_user_id and status = 'proposed';

  insert into public.growth_plans (
    intake_id, user_id, version, goal, formulation, milestones,
    current_focus, first_step, model_name, prompt_version
  ) values (
    p_intake_id, p_user_id, v_version, p_goal, p_formulation, p_milestones,
    p_current_focus, p_first_step, p_model_name, p_prompt_version
  ) returning * into v_plan;

  update public.growth_intakes
  set status = 'proposed', completed_at = coalesce(completed_at, now()), updated_at = now()
  where id = p_intake_id;

  if p_correction is not null and btrim(p_correction) <> '' then
    insert into public.growth_plan_evidence (
      user_id, intake_id, plan_id, kind, content
    ) values (
      p_user_id, p_intake_id, p_previous_plan_id, 'correction',
      jsonb_build_object('text', btrim(p_correction))
    );
  end if;

  return v_plan;
end;
$$;

revoke all on function public.persist_growth_plan_proposal(
  uuid, uuid, text, text, jsonb, text, jsonb, text, text, jsonb, jsonb, uuid, text
) from public, anon, authenticated;
grant execute on function public.persist_growth_plan_proposal(
  uuid, uuid, text, text, jsonb, text, jsonb, text, text, jsonb, jsonb, uuid, text
) to service_role;

create or replace function public.claim_growth_plan_generation(
  p_user_id uuid,
  p_intake_id uuid,
  p_request_fingerprint text,
  p_previous_plan_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request_id uuid;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  if p_previous_plan_id is null then
    if not exists (
      select 1 from public.growth_intakes
      where id = p_intake_id and user_id = p_user_id and status = 'in_progress'
    ) then
      return null;
    end if;
  elsif not exists (
    select 1
    from public.growth_intakes intake
    join public.growth_plans plan on plan.intake_id = intake.id
    where intake.id = p_intake_id
      and intake.user_id = p_user_id
      and intake.status = 'proposed'
      and plan.id = p_previous_plan_id
      and plan.user_id = p_user_id
      and plan.status = 'proposed'
  ) then
    return null;
  end if;

  if (
    select count(*) from public.growth_generation_requests
    where user_id = p_user_id and created_at > now() - interval '1 hour'
  ) >= 10 then
    return null;
  end if;

  if exists (
    select 1 from public.growth_generation_requests
    where user_id = p_user_id
      and request_fingerprint = p_request_fingerprint
      and status = 'started'
      and created_at > now() - interval '2 minutes'
  ) then
    return null;
  end if;

  insert into public.growth_generation_requests (
    user_id, intake_id, request_fingerprint
  ) values (
    p_user_id, p_intake_id, p_request_fingerprint
  ) returning id into v_request_id;

  return v_request_id;
end;
$$;

create or replace function public.finish_growth_plan_generation(
  p_request_id uuid,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_status not in ('completed', 'failed') then
    raise exception 'Invalid generation status';
  end if;
  update public.growth_generation_requests
  set status = p_status, finished_at = now()
  where id = p_request_id and status = 'started';
end;
$$;

revoke all on function public.claim_growth_plan_generation(uuid, uuid, text, uuid)
  from public, anon, authenticated;
grant execute on function public.claim_growth_plan_generation(uuid, uuid, text, uuid)
  to service_role;
revoke all on function public.finish_growth_plan_generation(uuid, text)
  from public, anon, authenticated;
grant execute on function public.finish_growth_plan_generation(uuid, text)
  to service_role;

create or replace function public.confirm_growth_plan(p_plan_id uuid)
returns public.growth_plans
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_plan public.growth_plans;
begin
  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text, 0));

  select * into v_plan from public.growth_plans
  where id = p_plan_id and user_id = auth.uid() and status = 'proposed'
  for update;

  if not found then
    raise exception 'Proposed growth plan not found';
  end if;

  update public.growth_plans
  set status = 'superseded'
  where user_id = auth.uid() and status = 'active';

  update public.growth_plans
  set status = 'active', confirmed_at = now()
  where id = p_plan_id
  returning * into v_plan;

  update public.growth_plans
  set status = 'rejected'
  where user_id = auth.uid() and status = 'proposed' and id <> p_plan_id;

  update public.growth_intakes
  set status = 'confirmed', updated_at = now()
  where id = v_plan.intake_id and user_id = auth.uid();

  insert into public.growth_plan_evidence (
    user_id, intake_id, plan_id, kind, content
  ) values (
    auth.uid(), v_plan.intake_id, v_plan.id, 'confirmation',
    jsonb_build_object('confirmed', true)
  );

  return v_plan;
end;
$$;

revoke all on function public.confirm_growth_plan(uuid) from public, anon;
grant execute on function public.confirm_growth_plan(uuid) to authenticated;

grant select, insert, update on public.growth_intakes to authenticated;
grant select on public.growth_plans to authenticated;
grant select on public.growth_plan_evidence to authenticated;
grant select, insert, update, delete on public.growth_event_preferences to authenticated;
grant select on public.growth_generation_requests to authenticated;
